default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: overcome
  username: en9in33r
  password: Holyshit11

test:
  <<: *default
  database: overcome
  username: en9in33r
  password: Holyshit11

production:
  <<: *default
  database: overcome
  username: en9in33r
  password: Holyshit11
